### ISSUE TITLE
[bug] FlaskDynaconf doesn't handle __contains__

### ISSUE THREAD

**Issue by davidism** [rochacbruno/dynaconf#501]
**Describe the bug**

Checking `key in app.config` returns `False` if the key is only set on `app.config` after the extension is initialized. However, accessing `app.config[key]` still works. If the key was set before initializing the extension, or through an env var, it correctly reports `True`.

This is important for extensions like Flask-SQLAlchemy. It checks if the key `SQLALCHEMY_DATABASE_URI` is set and shows a warning otherwise, incorrectly in this case.

**To Reproduce**

```python
from dynaconf import FlaskDynaconf
from flask import Flask

dynaconf = FlaskDynaconf()
app = Flask(__name__)
dynaconf.init_app(app)
app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"

print("SQLALCHEMY_DATABASE_URI" in app.config)  # False, should be True
print(app.config["SQLALCHEMY_DATABASE_URI"])  # sqlite:///app.db
```

**Expected behavior**

The `in` operator reports the correct result when a key is set after calling `init_app()`.

**Environment (please complete the following information):**

 - OS: Linux/Arch
 - Dynaconf 3.1.2
 - Flask 1.1.2

**Comment by rochacbruno** [comment]
Thanks for reporting @davidism I think we miss __contains__ implementation in the main `Dynaconf` class, I will work on it ASAP.

**Comment by Mdslino** [comment]
@rochacbruno something like that #502?

**Comment by damian-t** [comment]
Any update on this (https://github.com/rochacbruno/dynaconf/pull/502)? I would love to see this in the next release

**Comment by rochacbruno** [comment]
@Mdslino please turn your draft into a PR I will review and merge ASAP :)

**Comment by Mdslino** [comment]
Done.

**Comment by Mdslino** [comment]
> @Mdslino please turn your draft into a PR I will review and merge ASAP :)

Done.

**Comment by damian-t** [comment]
Thanks for the release @rochacbruno . #522 didn't solve this though as some of the changes of @Mdslino were accidentally(?) reverted.

`
    dynaconf = FlaskDynaconf()
    app = Flask(__name__)
    dynaconf.init_app(app)
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"

    print("SQLALCHEMY_DATABASE_URI" in app.config)  # False, should be True
    print(app.config["SQLALCHEMY_DATABASE_URI"])  # sqlite:///app.db
`
still applies

**Comment by davidism** [comment]
Yeah, I haven't 100% tracked it down yet, but updating to 3.1.3 causes the Flask config to raise `KeyError`.

**Comment by rochacbruno** [comment]
@davidism @damian-t so 3.1.4 is on the way

**Comment by rochacbruno** [comment]
passing CI I will do the hotfix release.

**Comment by rochacbruno** [comment]
Must be fixed in https://github.com/rochacbruno/dynaconf/releases/tag/3.1.4 please reopen if any more issue.

thanks :)
